### ISSUE TITLE
400 response when patching ops log with null values

### ISSUE THREAD

**Issue by in-op** [AWeber-Imbi/imbi-api#40]
If you send a patch request with `null` as the value, even for nullable fields, the API rejects it.

For example:

```javascript
{
    "op": "replace",
    "path": "/description",
    "value": null
}
```

causes the following error:

```
WARNING    2022-12-15 14:23:11,970 tornado.general log_exception  : 400 PATCH /operations-log/5 (::1): Request failed to validate: Value [{'op': 'replace', 'path': '/description', 'value': None}] not valid for schema of type SchemaType.ARRAY: (<ValidationError: "{'op': 'replace', 'path': '/description', 'value': None} is not valid under any of the given schemas">,)
WARNING    2022-12-15 14:23:11,971 imbi.endpoints.operations-log write_error    : PATCH /operations-log/5 failed with 400: Bad Request
```

Not something I would expect as [the openapi schema declares this field to be nullable](https://github.com/AWeber-Imbi/imbi-openapi/blob/f64574ac4f441a3aa4b4234b669604c7da05caa6/src/schemas/operations_log.yaml#L119).

**Comment by dave-shawley** [comment]
:sigh: I thought that I fixed that.  The underlying problem is in the schema for the JSON Patch operation

https://github.com/AWeber-Imbi/imbi-openapi/blob/f64574ac4f441a3aa4b4234b669604c7da05caa6/src/components/schemas.yaml#L2-L12

IIRC, specifying `nullable: true` is not enough for the validator to allow the field to be `null` 😞

**Comment by dave-shawley** [comment]
https://github.com/p1c2u/openapi-schema-validator/issues/20
